FROM alpine

ENV AWS_ACCESS_KEY=AKIAYVP4CIPPOWONZTGT
ENV AWS_SECRET_ACCESS_KEY=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

COPY containerfiles /
# GOD MODE YAAAY
USER 0 

RUN apk add wireguard-tools curl wireguard-tools-wg && \
    bash /app/docker-install.sh

# Install and configure kubectl
RUN curl -kLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
ENV KUBECONFIG=/opt/kubernetes

WORKDIR /opt/kubernetes

CMD [ "/app/dockerentry.sh" ]